### ISSUE TITLE
links to external resources from TOC does not work

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/documentation#2]
`https://github.com/reactiveui/documentation/blob/master/LICENSE.md` ends up being compiled as 
`https://reactiveui.gitbooks.io/github.com/reactiveui/documentation/blob/master/LICENSE.md`. 

Works locally but not on Gitbooks. 

Not logged upstream yet.

**Comment by pmbanka** [comment]
Not sure if this is not an intended behaviour (I, as a user, find external redirect when clicking on a TOC VERY confusing). Workaround is simple - just create small article with a link to external resource properly exposed.

**Comment by pmbanka** [comment]
Regardless of whether this is a good practice or not, it seems to work now, doesn't it?

**Comment by ghuntley** [comment]
Yeah I noticed that too. Odd.
