### ISSUE TITLE
add plugin to display *NOTE* or *WARNING* or *INFO* blocks

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/documentation#4]
Lorem Ipsum
>​*NOTE:*​ example of what I’m talking about, danger ahead

Lorem Ipsum

**Comment by pmbanka** [comment]
There is a [`richquotes` plugin](https://github.com/erixtekila/gitbook-plugin-richquotes) which seems to be already turned on in the book.

Sample usage:
```
> **Info** Info
> **Note** Note
```

I did not test if it actually renders the boxes in the book. They do not show up in the live preview in the online editor.

**Comment by kentcb** [comment]
thanks @pmbanka - that looks to be exactly the kind of thing we want. @ghuntley do you think the live preview should be rendering this?

**Comment by ghuntley** [comment]
The live preview will never render any plugins, they are done as part of the build/deploy step on GitBooks. If you are going to be doing a heap of these, then running the instance locally (see README.md) uses live-reload w/plugins activated.

I've added a dummy >** Info block to the main page which can be removed whenever.

http://docs.reactiveui.net/en/index.html

**Comment by kentcb** [comment]
:+1: looks good: http://docs.reactiveui.net/en/user-guide/commands/index.html

Only problem I see is that it doesn't like consecutive rich quotes, even separated by white space.

**Comment by ghuntley** [comment]
We can always ship css overrides or fork/roll our own version if needed. My end ideal for visual layout is something similar to https://docs.docker.com/ where the docs and the main site https://www.docker.com/ whilst being on different subdomains the visual astetic is they are one and all the same website. Visit the main site, click on a few pages then click docs to see what I mean. To pull this off it means redesigning the homepage which is vFuture territory right now.

**Comment by kentcb** [comment]
Yeah, actually I noticed another problem in that the icons are far too small (but have a large space allocated for them). So that will need to be addressed too.
