### ISSUE TITLE
provide single source of truth by unpublishing/deleting old documentation

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/documentation#5]
Each stage as appropriate:
- [x] Unpublish reactiveui.readthedocs.org
- [x] Delete reactiveui@master/docs/*
- [ ] Delete reactiveui@docs branch.
- [x] Delete ghuntley@readthedocs branch.

**Comment by GiusepeCasagrande** [comment]
What need to be done before deleting reactiveui@master/docs/* and reactiveui@docs branch?

**Comment by ghuntley** [comment]
I'd like to delete this repository and move its content under reactiveui main repo once development dies down. At this stage we are using gitbook WYSIWYG editor which allows rapid writing without going through PRs.

I'm hesitant to unpublish the docs branches until stuff gets fleshed out more / verified that insights and perspectives don't get lost. 

If you think we got enough coverage I'll raise a PR to clear out the old docs.

**Comment by ghuntley** [comment]
Question: are missing docs better than inconsistent docs? If so let's nuke the main repo asap to reduce possibilities of confusion.

**Comment by GiusepeCasagrande** [comment]
I prefer missing docs over inconsistent/out of date ones. 

And besides that, as a rookie, I don't remember looking into the docs inside the main repo, but I do look into the http://docs.reactiveui.net/en/index.html quite often. 

Just to be clear, if I understood correctly, the idea is to move the updated documents over the old ones, right?

**Comment by ghuntley** [comment]
Send in a PR that recursively removes https://github.com/reactiveui/ReactiveUI/tree/develop/docs and all content please.

Eventually when the contents found in this repo mature it will make sense to move it into main repo docs and then start enforcing that PRs must update docs when a new feature or change is done.

**Comment by ghuntley** [comment]
We can close this off now. If someone stumbles.on the docs branch then good for them. There's definitely content in there that could be mifrsted.
