### ISSUE TITLE
Should we use the term "Functional Reactive Programming"?

### ISSUE THREAD

**Issue by pmbanka** [reactiveui/documentation#6]
It seems to mean something else than we indicate in the docs. [From Rx intro page](http://reactivex.io/intro.html):

> It is sometimes called “functional reactive programming” but this is a misnomer. ReactiveX may be functional, and it may be reactive, but “functional reactive programming” is a different animal. One main point of difference is that functional reactive programming operates on values that change continuously over time, while ReactiveX operates on discrete values that are emitted over time. (See Conal Elliott’s work for more-precise information on functional reactive programming.)

So I guess we should stick to the term "Reactive Programming" instead.

**Comment by paulcbetts** [comment]
Yes, because this is marketing copy and doesn't have to be accurate, only interesting and relevant. When average people look for FRP, this is what they want

**Comment by shiftkey** [comment]
Belated :+1: on using FRP - we're building upon ReactiveX and yeah, it's basically marketing copy...
